# fly.toml file generated for blue-pine-3848 on 2023-04-11T01:54:08+01:00

app = "blue-pine-3848"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "bos"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  http_checks = []
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
